[package]
name = "vst3-impl"
version = "0.1.0"
authors = ["Mike Hilgendorf <mike@hilgendorf.audio>"]
edition = "2018"


[dependencies]
vst3-interfaces = {path = "../vst3-interfaces" }
vst3-derive = {path = "../vst3-derive"}