[package]
name = "vst3-interfaces"
version = "0.1.0"
authors = ["Mike Hilgendorf <mike@hilgendorf.audio>"]
edition = "2018"
license = "GPLv3"
description = "VST3 interfaces"

[dependencies]
widestring = "0.4.0"